include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "split-central input-trackball input-listener"
    artifact-name: torabo_tsuki_lp_left_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    artifact-name: torabo_tsuki_lp_right_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    artifact-name: torabo_tsuki_lp_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "split-central input-trackball input-listener"
    artifact-name: torabo_tsuki_lp_right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "input-trackball input-split"
    artifact-name: torabo_tsuki_lp_double_ball_left_peripheral
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "split-central input-trackball input-listener input-split-listener"
    artifact-name: torabo_tsuki_lp_double_ball_right_central
  - board: bmp_boost
    shield: settings_reset
